[project]
name = "tpv"
version = "0.1.0"
description = "Total Perspective Vortex - EEG motor imagery BCI (42 School)"
readme = "README.md"
authors = [
    { name = "Gabriel Correia Lima Cardoso", email = "gabrielclcardoso@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "mne>=1.13.2",
    "numpy>=2.5.4",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
]

[project.scripts]
tpv = "tpv.cli:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
